"""User table

Revision ID: 3d368e91d42c
Revises: 
Create Date: 2019-07-05 12:29:50.024985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d368e91d42c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=75), nullable=True),
    sa.Column('medium', sa.String(length=20), nullable=True),
    sa.Column('portrait', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_medium'), 'user', ['medium'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_medium'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
